import = ["~/codes/GitHub/dotfiles/alacritty/themes/rose_pine.toml"]

[env]
TERM = "xterm-256color"

[colors.primary]
background = "#272727"

[cursor]
unfocused_hollow = true
thickness = 0.15
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 15.0

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "-2", "tmux a -t config || tmux new -s config"]

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Light"

[window.dimensions]
columns = 80
lines = 25

[window.position]
x = 200
y = 100

[window]
startup_mode = "Maximized"

dynamic_padding = true
opacity = 0.95
decorations = "None"

[window.padding]
x = 8
y = 6

[[keyboard.bindings]]
key = "V"
mods = "Super"
action = "Paste"

[scrolling]
history = 10000
multiplier = 3
