import = ["~/codes/GitHub/dotfiles/alacritty/themes/onedark.toml"]

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Beam"

[colors.primary]
# background = "#111111"

[colors.cursor]
# background = "#ffffff"
text = "CellBackground"

[font]
size = 15.0

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "-2", "tmux a -t config || tmux new -s config"]

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Light"

[window.dimensions]
columns = 80
lines = 25

[window.position]
x = 200
y = 100

[window]
startup_mode = "Maximized"

dynamic_padding = true
# opacity = 0.92
# blur = true
decorations = "None"

[window.padding]
x = 8
y = 6

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[scrolling]
history = 10000
multiplier = 3
