import = [
  # "~/Documents/repos/dotfiles/alacritty/themes/rose_pine.toml",
  # "~/Documents/repos/dotfiles/alacritty/themes/tokyonight_moon.toml",
  # "~/Documents/repos/dotfiles/alacritty/themes/tokyonight_storm.toml",
  "~/Documents/repos/dotfiles/alacritty/themes/tokyonight_night.toml",
]

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Beam"
blinking = "Always"

# [colors.cursor]
# text = "#e0def4"
# cursor = "#524f67"
#
# [colors.vi_mode_cursor]
# text = "#e0def4"
# cursor = "#FFFFFF"

[font]
size = 12.0

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux a -t base || tmux new -s base"]

[font.normal]
family = "MonaspiceNe Nerd Font Mono"
style = "Light"

[font.italic]
style = "Light Italic"

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Regular Italic"

[window.dimensions]
columns = 80
lines = 25

[window.position]
x = 200
y = 100

[window]
startup_mode = "Fullscreen"

dynamic_padding = true
opacity = 0.95
blur = false
decorations = "Transparent"

[window.padding]
x = 6
y = 6
