
[env]
TERM = "xterm-256color"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
unfocused_hollow = true
thickness = 0.15
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 15.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[font.italic]
family = "FiraCode Nerd Font"
style = "Light Italic"

[font.bold]
family = "FiraCode Nerd Font"
style = "Light"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Light Italic"


[window.position]
x = 200
y = 100

[window]
startup_mode = "Maximized"

decorations = "None"

[[keyboard.bindings]]
key = "V"
mods = "Super"
action = "Paste"

[general]
import = ["~/codes/GitHub/dotfiles/alacritty/themes/nightfox.toml"]
