import = [
  "~/codes/GitHub/dotfiles/alacritty/themes/rose_pine.toml",
]

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Beam"

[colors.primary]
# background = "#1d1f20"

# [colors.cursor]
# text = "CellBackground"
# background = "#60b579"

[font]
size = 16.0

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "-2", "tmux a -t config || tmux new -s config"]

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.italic]

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Regular Italic"

[window.dimensions]
columns = 80
lines = 25

[window.position]
x = 200
y = 100

[window]
startup_mode = "Maximized"

dynamic_padding = true
# opacity = 0.99
# blur = true
decorations = "None"

[window.padding]
x = 8
y = 6

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[scrolling]
history = 10000
multiplier = 3
