import = [
  # "~/Documents/repos/dotfiles/alacritty/themes/rose_pine.toml",
  # "~/Documents/repos/dotfiles/alacritty/themes/rose_pine_moon.toml",
  # "~/Documents/repos/dotfiles/alacritty/themes/tokyonight_moon.toml",
  # "~/Documents/repos/dotfiles/alacritty/themes/tokyonight_storm.toml",
  # "~/Documents/repos/dotfiles/alacritty/themes/tokyonight_night.toml",
  "~/Documents/repos/dotfiles/alacritty/themes/catppuccin-mocha.toml",
]

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Beam"
blinking = "Always"

[colors.cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#FFFFFF"

[font]
size = 15.0

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "-2", "tmux a -t base || tmux new -s base"]

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
style = "Regular Italic"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[window.dimensions]
columns = 80
lines = 25

[window.position]
x = 200
y = 100

[window]
startup_mode = "Maximized"

dynamic_padding = true
# opacity = 0.97
# blur = false
decorations = "None"

[window.padding]
x = 8
y = 6

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "y"
mods = "Control"
action = "Copy"

[scrolling]
history = 10000
multiplier = 3
