[cursor]
style = "Block"

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Thin"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.95
blur = true
decorations = "buttonless"

[window.padding]
x = 6
y = 6

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.primary]
background = '#011627'
foreground = '#bdc1c6'
bright_foreground = '#eeeeee'

[colors.selection]
text = '#080808'
background = '#b2ceee'

[colors.normal]
black = '#1d3b53'
red = '#fc514e'
green = '#a1cd5e'
yellow = '#e3d18a'
blue = '#82aaff'
magenta = '#c792ea'
cyan = '#7fdbca'
white = '#a1aab8'

[colors.bright]  
black = '#7c8f8f'
red = '#ff5874'
green = '#21c7a8'
yellow = '#ecc48d'
blue = '#82aaff'
magenta = '#ae81ff'
cyan = '#7fdbca'
white = '#d6deeb'
