[packages]
brew = [ 'ghostty', 'nvim', 'eza', 'gitmux', 'starship' ]
app = [ 'Rectangle', 'Zed' ]

[configs.app]
'RectangleProConfig.json' = '~/Library/Application Support/Rectangle Pro/RectangleProConfig.json'

[configs.symlink]
'.agents' = '~/.agents'
'.pi' = '~/.pi'
'.tmux.conf' = '~/.tmux.conf'
'.zshutils' = '~/.zshutils'
'ghostty' = '~/.config/ghostty'
'wezterm' = '~/.config/wezterm'
'lazygit' = '~/.config/lazygit'
'herdr/config.toml' = '~/.config/herdr/config.toml'
'mise' = '~/.config/mise'
'nvim' = '~/.config/nvim'
'zed' = '~/.config/zed'
'starship.toml' = '~/.config/starship.toml'

[[commands]]
name = 'Register Herdr default tabs plugin'
command = [ 'herdr', 'plugin', 'link', 'configs/herdr/plugins/default-tabs' ]
