[packages]
brew = [ 'ghostty', 'nvim', 'eza', 'gitmux' ]
manual = [ 'omz' ]
app = [ 'Rectangle', 'Zed' ]

[configs.app]
'RectangleProConfig.json' = '~/Library/Application Support/Rectangle Pro/RectangleProConfig.json'

[configs.symlink]
'.zshutils' = '~/.zshutils'
'.tmux.conf' = '~/.tmux.conf'
'ghostty' = '~/.config/ghostty'
'lazygit' = '~/.config/lazygit'
'mise' = '~/.config/mise'
'nvim' = '~/.config/nvim'
'opencode' = '~/.config/opencode'
'zed' = '~/.config/zed'
'starship.toml' = '~/.config/starship.toml'
