local key = vim.keymap.set

key("n", "<Esc>", "<cmd>nohl<cr>", { desc = "No highlight" })
key("n", ";", "/<BS>", { desc = "Clear command line" })
key("n", "H", "", { desc = "Unbind" })
key("n", "L", "", { desc = "Unbind" })
key("v", "J", ":m '>+1<cr>gv=gv", { desc = "Move visually selected line down" })
key("v", "K", ":m '<-2<cr>gv=gv", { desc = "Move visually selected line up" })
key("n", "J", "mzJ`z", { desc = "Join line and keep cursor steady" })
key("n", "<C-d>", "<C-d>zz", { desc = "Half-page down and recenter" })
key("n", "<C-u>", "<C-u>zz", { desc = "Half-page up and recenter" })
key("n", "n", "nzzzv", { desc = "Next match and open folds" })
key("n", "N", "Nzzzv", { desc = "Previous match and open folds" })
key({ "n", "v" }, "<leader>d", [["_d]], { desc = "Delete to blank register" })
key("x", "<leader>p", [["_dP]], { desc = "Paste without yanking replaced text" })
key("n", "<leader>rp", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]], { desc = "Replace word under cursor" })

key("n", "<leader>vd", vim.diagnostic.open_float, { desc = "Open diagnostics" })
key("n", "]d", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
key("n", "[d", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })

key("n", "<leader>=-", function()
  vim.cmd.packadd("persistence")
  require("persistence").setup({})
  require("persistence").load()
end, { desc = "Load last session" })

key("n", "<C-b>", "<cmd>NvimTreeFindFileToggle<cr>", { desc = "Toggle Nvim Tree" })
key("n", "<leader>dvo", "<cmd>DiffviewOpen<cr>", {desc = "Diff view (working copy)" })
key("n", "<leader>dvc", "<cmd>DiffviewClose<cr>", {desc = "Close diff view" })
key("n", "<leader>dvh", "<cmd>DiffviewFileHistory %<cr>", {desc = "File history (current)" })
key("n", "<leader>dvfh", "<cmd>DiffviewFileHistory<cr>", {desc = "File history (repo)" })
